### ISSUE TITLE
Ambiguous max mob injections for RFTools syringes

### ISSUE THREAD

**Issue by josephcsible** [AllTheMods/ATM-3#446]
https://github.com/AllTheMods/ATM-3/blob/a706b921f4b00121e67f95b6c284c51dcae50b9f/overrides/config/rftools/rftools.cfg#L398-L399

https://github.com/AllTheMods/ATM-3/blob/a706b921f4b00121e67f95b6c284c51dcae50b9f/overrides/config/rftools/dimensions.cfg#L31-L32

RFTools and RFTools Dimensions were never supposed to have different values for the number of mob injections required to fill a syringe. Having these settings differ means that it's impossible to craft any mob dimlet in RFTools Dimensions. Please change either the former setting to 64, if that's what you want the syringe size to be, or change the latter setting back to 10. (The fact that this mistake is possible was itself a bug in RFTools Dimensions, which I fixed in McJty/RFToolsDimensions@dac47f7. In RFTools Dimensions 5.53 and later, the dimensions.cfg setting is simply removed in favor of the rftools.cfg setting.)

**Comment by josephcsible** [comment]
Note that once this is fixed, you can remove [the custom recipe for a dragon dimlet](https://github.com/AllTheMods/ATM-3/blob/a706b921f4b00121e67f95b6c284c51dcae50b9f/overrides/scripts/atm_general_misc.zs#L332-L346), as the usual dimlet workbench recipe will then work even though the syringe is disabled in the spawner.

**Comment by Boomflex** [comment]
Fixed in dev.

Thanks.

**Comment by josephcsible** [comment]
I don't see the fix (assuming that by "dev", you mean the dev branch).

**Comment by Boomflex** [comment]
Not pushed it to the branch yet. 

It’s on my Dev copy locally.

**Comment by josephcsible** [comment]
@Boomflex I still don't see either the config fix or the removal of the custom recipe in Git. Did you ever push your dev copy?

**Comment by Yoosk** [comment]
> 
> 
> @Boomflex I still don't see either the config fix or the removal of the custom recipe in Git. Did you ever push your dev copy?

Boomflex is no longer developer of the pack, doubt he will asnwer.

**Comment by josephcsible** [comment]
Ah. I'll just PR the necessary changes then.
